image: Visual Studio 2017

install:
  - nuget restore

configuration:
  - Release

build:
  project: Its.Log.sln
  publish_nuget: true

after_build:
    - nuget pack Recipes\AssemblyVersionSensor.nuspec -p "Configuration=Release;Platform=AnyCPU" 
    - nuget pack Recipes\WebApiTelemetry.nuspec -p "Configuration=Release;Platform=AnyCPU"
    - nuget pack Its.Log\Its.Log.nuspec -p "Configuration=Release;Platform=AnyCPU" 

test:
  assemblies:
    - '**\*Tests.dll'

artifacts:
  - path: '*.nupkg'

